includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 2
seed: 0
deterministic: true
data_root: /data/fewshot/tiered_imagenet
#! basic
batch_size: 128
episode_size: 4
epoch: 100
test_epoch: 5
train_episode: 2000
test_episode: 600
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/fewshot/tiered_imagenet
#! optimizer
lr_scheduler:
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: null
#! backbone
backbone:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: resnet18
#! classifier
classifier:
  kwargs:
    feat_dim: 512
    inner_param:
      lr: 0.001
      test_iter: 10
      train_iter: 5
  name: ANIL
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: null
resume: false
resume_path: ~
save_interval: 10
save_part:
  - emb_func  
parallel_part:
  - emb_func




