includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
epoch: 100
test_epoch: 5
train_episode: 5000
test_episode: 600
episode_size: 4
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/fewshot/tiered_imagenet
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: ~
#! backbone
backbone:
  kwargs:
    keep_prob: 0.0
  name: resnet12
#! classifier
classifier:
  kwargs:
    feat_dim: 640
    inner_param:
      lr: 0.001
      test_iter: 10
      train_iter: 5
  name: ANIL
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: ~
log_paramerter: false
pretrain_path: ~
resume: false
resume_path: ~
save_interval: 10
save_part:
  - emb_func
parallel_part:
  - emb_func
