includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
epoch: 100
test_epoch: 5
test_episode: 600
batch_size: 64
episode_size: 1
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/wzy/miniImageNet--ravi
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 100
  name: StepLR
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: ~
#! backbone
backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
    last_block_stride: 2
  name: resnet18
#! classifier
classifier:
  kwargs:
    feat_dim: 512
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          dampening: 0.9
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.001
        name: SGD
      inner_train_iter: 100
    num_class: 400
  name: Baseline
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: ~
log_paramerter: false
pretrain_path: ~
resume: false
resume_path: ~
tag: ~
tb_scale: 1.6666666666666667
save_interval: 50
save_part:
  - emb_func  
parallel_part:
  - emb_func




