includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Baseline.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
batch_size: 16
episode_size: 1
epoch: 400
test_epoch: 5
train_episode: 60000
test_episode: 600
shot_num: 5
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/wzy/miniImageNet--ravi
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 100
  name: StepLR
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: null
#! backbone
backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
    maxpool_last2: true
  name: resnet12
#! classifier
classifier:
  kwargs:
    feat_dim: 640
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          dampening: 0.9
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.001
        name: SGD
      inner_train_iter: 100
    num_class: 200
  name: Baseline
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: null
resume: true
resume_path: ./results/Baseline-miniImageNet--ravi-Conv64F-5-5-Dec-01-2021-06-52-22
resume_path: ~
tag: null
tb_scale: 100.0
save_interval: 50
save_part:
  - emb_func  
parallel_part:
  - emb_func




