includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
epoch: 100
test_epoch: 5
val_per_epoch: 1
train_episode: 5000
test_episode: 600
episode_size: 4
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/wzy/tiered_imagenet
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 10
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.0006
  name: Adam
  other:
    emb_func: 0.0006
#! backbone
backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
#! classifier
classifier:
  kwargs:
    feat_dim: 512
    inner_param:
      classifier_lr: 0.0
      extractor_lr: 0.3
    testing_method: Once_update
  name: BOIL
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: ~
log_paramerter: false
pretrain_path: ~
resume: false
resume_path: ~
tb_scale: 3.3333333333333335
tag: null
save_interval: 10
save_part:
  - emb_func  
parallel_part:
  - emb_func




