includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
batch_size: 128
episode_size: 4
epoch: 100
test_epoch: 5
train_episode: 4000
test_episode: 600
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/miniImageNet--ravi
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 0.05
    step_size: 25
  name: StepLR

optimizer:
  kwargs:
    betas:
    - 0.5
    - 0.9
    lr: 0.001
  name: Adam
  other: null
#! backbone
backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: true
    maxpool_last2: false
    negative_slope: 0.2
  name: Conv64F
#! classifier
classifier:
  kwargs:
    n_local: 441
  name: ConvMNet
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: ~
resume: false
tb_scale: 6.666666666666667
tag: null
resume_path: ~
save_interval: 10
workers: 16
save_part:
  - emb_func  
parallel_part:
  - emb_func




