includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/DN4.yaml
- backbones/Conv64F.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
epoch: 100
test_epoch: 5
train_episode: 5000
test_episode: 600
batch_size: 64
episode_size: 4
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/yxs/tiered_imagenet
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 50
  name: StepLR
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: null
#! backbone
backbone:
  kwargs:
    is_flatten: false
    maxpool_last2: false
  name: resnet12
#! classifier
classifier:
  kwargs:
    n_k: 3
  name: DN4
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: ~
log_paramerter: false
pretrain_path: ~
resume: false
resume_path: ~
tb_scale: 8.333333333333334
tag: ~
save_interval: 10
save_part:
  - emb_func  
parallel_part:
  - emb_func




