includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
batch_size: 128
episode_size: 4
epoch: 100
test_epoch: 5
train_episode: 5000
test_episode: 600
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/tiered_imagenet
#! optimizer
lr_scheduler:
  kwargs:
    T_max: 100
    eta_min: 0
  name: CosineAnnealingLR

optimizer:
  kwargs:
    lr: 0.0005
  name: Adam
#! backbone
backbone:
  kwargs: null
  name: resnet12
#! classifier
classifier:
  kwargs:
    encoder_penalty_weight: 1.0e-09
    feat_dim: 640
    hid_dim: 64
    inner_para:
      finetune_iter: 5
      finetune_lr: 0.01
      iter: 5
      lr: 0.01
    kl_weight: 0.001
    orthogonality_penalty_weight: 0.001
  name: LEO
#! result
result_root: ./results
#! other
port: 34441
pretrain_path: ./results/RFS-simple-tiered_imagenet-resnet12-Table2/checkpoints/emb_func_best.pth
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: ~
resume: false
tb_scale: 3.3333333333333335
tag: null
workers: 16
resume_path: ~
save_interval: 10
save_part:
  - emb_func  
parallel_part:
  - emb_func




