includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Negative_Margin.yaml
- backbones/resnet18.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
batch_size: 128
episode_size: 4
epoch: 100
test_epoch: 5
train_episode: 100
test_episode: 600
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/yxs/tiered_imagenet
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 10
  name: StepLR

optimizer:
  kwargs:
    lr: 0.003
    weight_decay: 0.00005
  name: Adam
  other: null
#! backbone
backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
#! classifier
classifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      inner_batch_size: 4
      inner_margin: 0.0
      inner_optim:
        kwargs:
          dampening: 0.9
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.001
        name: SGD
      inner_scale_factor: 5.0
      inner_train_iter: 100
    margin: -0.02
    num_class: 351
    scale_factor: 30
  name: NegNet
#! result
result_root: ./results
#! other
warmup_params:
  epoch: 0
  multiplier: 16
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: ~
resume: false
tb_scale: 0.16666666666666666
tag: null
workers: 8
resume_path: ~
save_interval: 10
save_part:
  - emb_func  
parallel_part:
- emb_func
- classifier
- distill_layers




