includes:
- headers/data.yaml
- headers/device.yaml
- headers/losses.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/SKD.yaml
- backbones/resnet12.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
batch_size: 128
episode_size: 4
epoch: 100
test_epoch: 5
train_episode: 1000
test_episode: 600
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/wzy/miniImageNet--ravi
#! optimizer
lr_scheduler:
  kwargs:
    T_max: 100
    eta_min: 1.0e-06
  name: CosineAnnealingLR

optimizer:
  kwargs:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  name: SGD
  other:
    emb_func: 0.001
#! backbone
backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
    maxpool_last2: true
  name: resnet12
#! classifier
classifier:
  kwargs:
    alpha: 0.1
    cls_classifier_path: ./results/SKDModel-miniImageNet--ravi-resnet12-5-1-Aug-28-2021-07-01-15/checkpoints/cls_classifier_best.pth
    emb_func_path: ./results/SKDModel-miniImageNet--ravi-resnet12-5-1-Aug-28-2021-07-01-15/checkpoints/emb_func_best.pth
    feat_dim: 640
    gamma: 1.0
    is_distill: true
    kd_T: 2
    num_class: 64
  name: SKDModel
#! result
result_root: ./results
#! other
loss:
  kwargs: null
  name: CrossEntropyLoss
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: ~
resume: false
tb_scale: 0.16666666666666666
tag: null
workers: 8
resume_path: ~
save_interval: 10
save_part:
  - emb_func
  - cls_classifier
  - rot_classifier
parallel_part:
  - emb_func




