includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
batch_size: 128
episode_size: 4
epoch: 100
test_epoch: 5
train_episode: 5000
test_episode: 600
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: /data/yxs/tiered_imagenet
#! optimizer
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR

optimizer:
  kwargs:
    lr: 0.00025
    weight_decay: 0.0005
  name: Adam
  other: null
#! backbone
backbone:
  kwargs: null
  name: resnet18
#! classifier
classifier:
  kwargs:
    feat_dim: 512
    hid_dim: 512
    sample_num: 10
  name: VERSA
#! result
result_root: ./results
#! other
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: ~
resume: false
tb_scale: 8.333333333333334
tag: null
workers: 16
resume_path: ~
save_interval: 10
save_part:
  - emb_func
parallel_part:
  - emb_func




